FUN = [
  "Kenapa sih kerang hidupnya di laut? Soalnya kalo hidupnya di darat namanya kering",
  "Pak, barusan saya mau masak, tapi tiba-tiba pancinya jalan sendiri nggak tau ke mana. Ternyata panci petualang",
  "Kalo kamu masih diselimuti masalah berarti kamu manusia, kao kamu diselimuti wijen berarti onde-onde.",
  "Kenapa nyamuk bunyinya nguung? Karena dia minumnya darah, coba kalo minumnya bensin, bunyinya jadi bruuum.",
  "Kalo cinta masih mandang fisik, suruh aja pacaran sama ikan karena ikan banyak fisiknya.",
  "Saya tadi beli obat tidur di apotek, saya bawa pulang pelan-pelan takut obatnya bangun.",
  "Anak saya ngeyel kuliah malah ngambil komputer, pas pulang ternyata mukanya bonyok.",
  "Di balik usapan tangan suami ke kepala istri, sebenarnya dia ingin memastikan di kepala istrinya nggak ada paku.",
  "Enak ya jadi maling banyak yang ngejar-ngejar dan nggak pake mandang fisik.",
  "Siapa nama asli nyamuk? Tatang! Kan ada lagunya: Cicak-cicak di dinding. Diam-diam merayap. Tatang seekor nyamuk, hap. Lalu ditangkap...",
  "Bundaran HI kalo di putarin 3x namanya jadi Bundaran HIHIHI",
  "Mau Liat Cowo Ganteng Ga? Nih Tap Aja @TheFvck4Ryn Ganteng Banget Cok Dia",
  "Cowo Terlucu Cuma @TheFvck4Ryn Doang Kak",
  "Mau Tau Ga Bot Music Yg Bisa Play Video Dan Anti Patah2 Dimana? Ya Cuma Di @SpotifyStream_Id Doang Lah",
  "HAHAHA LUCU BANGET SI KAMU JADI PENGEN DI EPAK DEH 🫨🥺",
  "Kak Lipkol Yug Ntar Aku Ajak Kenalan Sama Papah Aku Yg Ada Di Tanah Mau Ga?",
  "Asli Mana Kak? Aslinya Cuma Jadi Bahan Gabutnya Doang Kok :)",
  "Kok Kamu Lucu Kak? Mau Ga Jadi Bandar Slot?",
  "Kamu Tau Ga Bedanya Kamu Sama Kambing? Ga Tau Ya? Padahal Gd Bedanya, Sama Sama Bau Soalnya :)",
  "Kenapa Matahari Tenggelam? Karna Ga Bisa Berenang",
  "Kota Apa Yg Banyak Bapak2Nya? Purwadaddy.",
  "Bakso, Bakso Apa Yg Ga Boleh Di Liat Tapi Boleh Di Makan? Bakso Aurat.",
  "Burung, Burung Apa Yg Suka Nolak? Burung Gak Gak",
]
